[package]
name = "poly_it"
version = "0.1.0"
edition = "2021"
rust-version = "1.70.0"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/gifnksm/polynomial-rs"
description = "A library for manipulating polynomials"

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
num-traits = { version = "0.2.18", default-features = false, features = [
    "libm",
] }
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
serde = ["dep:serde"]

[package.metadata.release]
pre-release-replacements = [
    { file = "README.md", search = "polynomial = \"[0-9\\.]+\"", replace = "{{crate_name}} = \"{{version}}\"" },
    { file = "README.md", search = "polynomial = \\{version = \"[0-9\\.]+\"", replace = "{{crate_name}} = {version = \"{{version}}\"" },
]
